/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package variables;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class SQLEspañol extends javax.swing.JFrame {

    private Variables v= new Variables();
    private Numeros n= new Numeros();
    private Update u=new Update();
    private Delete d=new Delete();
    private Insert i=new Insert();
    private Select s= new Select();
    private ConexionBD Cxn;
    public boolean bandera=true;
     public int controlError;
    /**
     * Creates new form SQLEspañol
     */
    public SQLEspañol() {
       initComponents();
         Sintactico.setEnabled(false);
        Semantico.setEnabled(false);
        this.setSize(950, 700);
        this.setTitle("SQL Español");
        this.setResizable(false);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("sql1.png"));


        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        pestañaInicial = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cadena = new javax.swing.JTextField();
        Lexico = new javax.swing.JButton();
        Sintactico = new javax.swing.JButton();
        Semantico = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pestañaLexico = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultadosLexico = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultadosSintactico = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultadosSemantico = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        consulta = new javax.swing.JTextArea();
        consultaSQL = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Conexion = new javax.swing.JTabbedPane();
        PanelConexion = new javax.swing.JPanel();
        btnConexion = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        LblUsuario = new javax.swing.JLabel();
        LblPass = new javax.swing.JLabel();
        CajaUsuario = new javax.swing.JTextField();
        CajaPass = new javax.swing.JPasswordField();
        LblBases = new javax.swing.JLabel();
        btnBases = new javax.swing.JButton();
        ListaBases = new javax.swing.JComboBox();
        jScrollPane6 = new javax.swing.JScrollPane();
        Arbol = new javax.swing.JTree();
        LblBaseUso = new javax.swing.JLabel();

        jScrollPane5.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setIconImage(getIconImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/titulo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setAutoscrolls(true);
        jPanel3.setPreferredSize(new java.awt.Dimension(879, 829));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Operación en SQL");

        cadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadenaActionPerformed(evt);
            }
        });

        Lexico.setBackground(new java.awt.Color(0, 0, 0));
        Lexico.setForeground(new java.awt.Color(51, 51, 51));
        Lexico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aceptar.png"))); // NOI18N
        Lexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LexicoActionPerformed(evt);
            }
        });

        Sintactico.setBackground(new java.awt.Color(0, 0, 0));
        Sintactico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aceptar.png"))); // NOI18N
        Sintactico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SintacticoActionPerformed(evt);
            }
        });

        Semantico.setBackground(new java.awt.Color(0, 0, 0));
        Semantico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aceptar.png"))); // NOI18N

        Limpiar.setBackground(new java.awt.Color(0, 0, 0));
        Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/limpiar.png"))); // NOI18N
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lexico");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sintáctico");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Semántico");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Limpiar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cadena, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lexico)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sintactico)
                            .addComponent(jLabel4))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5))
                            .addComponent(Semantico))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(Limpiar)))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lexico)
                            .addComponent(Sintactico)
                            .addComponent(Semantico)))
                    .addComponent(Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pestañaInicial.addTab("SQLEspañol", jPanel2);

        pestañaLexico.setBackground(new java.awt.Color(153, 255, 0));

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));

        resultadosLexico.setBackground(new java.awt.Color(0, 0, 0));
        resultadosLexico.setColumns(20);
        resultadosLexico.setForeground(new java.awt.Color(0, 204, 0));
        resultadosLexico.setRows(5);
        jScrollPane1.setViewportView(resultadosLexico);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(347, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );

        pestañaLexico.addTab("Léxico", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 102, 51));

        resultadosSintactico.setBackground(new java.awt.Color(0, 0, 0));
        resultadosSintactico.setColumns(20);
        resultadosSintactico.setForeground(new java.awt.Color(51, 204, 0));
        resultadosSintactico.setRows(5);
        jScrollPane2.setViewportView(resultadosSintactico);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );

        pestañaLexico.addTab("Sintáctico", jPanel5);

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));

        resultadosSemantico.setBackground(new java.awt.Color(0, 0, 0));
        resultadosSemantico.setColumns(20);
        resultadosSemantico.setRows(5);
        jScrollPane3.setViewportView(resultadosSemantico);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(346, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );

        pestañaLexico.addTab("Semántico", jPanel6);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        consulta.setColumns(20);
        consulta.setRows(5);
        jScrollPane4.setViewportView(consulta);

        consultaSQL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sqlConsulta.png"))); // NOI18N

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Realizar Consulta");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consultaSQL)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(consultaSQL, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Realizar Consulta", jPanel7);

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Salir");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(30, 30, 30))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8))
        );

        PanelConexion.setBackground(new java.awt.Color(104, 157, 157));
        PanelConexion.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 0, 0)));

        btnConexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sql.png"))); // NOI18N
        btnConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConexionActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setText("Establecer Conexion:");

        LblUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LblUsuario.setForeground(new java.awt.Color(0, 51, 0));
        LblUsuario.setText("Usuario:");

        LblPass.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LblPass.setForeground(new java.awt.Color(0, 51, 0));
        LblPass.setText("Contraseña:");

        LblBases.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        LblBases.setForeground(new java.awt.Color(51, 51, 0));
        LblBases.setText("Mostrar Base de Datos");

        btnBases.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBases.setForeground(new java.awt.Color(0, 0, 102));
        btnBases.setText("Aceptar");
        btnBases.setEnabled(false);
        btnBases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBasesActionPerformed(evt);
            }
        });

        ListaBases.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar Base de Datos" }));
        ListaBases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaBasesActionPerformed(evt);
            }
        });

        Arbol.setBackground(new java.awt.Color(204, 204, 204));
        Arbol.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 0), 2, true), "Tablas"));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Base");
        Arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        Arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ArbolMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(Arbol);

        LblBaseUso.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        LblBaseUso.setForeground(new java.awt.Color(255, 255, 255));
        LblBaseUso.setText("Base de Datos en Uso:");

        javax.swing.GroupLayout PanelConexionLayout = new javax.swing.GroupLayout(PanelConexion);
        PanelConexion.setLayout(PanelConexionLayout);
        PanelConexionLayout.setHorizontalGroup(
            PanelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConexionLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(PanelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelConexionLayout.createSequentialGroup()
                        .addGroup(PanelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblUsuario)
                            .addComponent(LblPass))
                        .addGap(34, 34, 34)
                        .addGroup(PanelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CajaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(CajaPass)))
                    .addGroup(PanelConexionLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(btnConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96)
                .addGroup(PanelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblBases)
                    .addComponent(ListaBases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblBaseUso)
                    .addGroup(PanelConexionLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnBases)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        PanelConexionLayout.setVerticalGroup(
            PanelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConexionLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PanelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblUsuario)
                    .addComponent(CajaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblBases))
                .addGroup(PanelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelConexionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBases)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(LblBaseUso)
                        .addGap(18, 18, 18)
                        .addComponent(ListaBases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(PanelConexionLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(PanelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblPass)
                            .addComponent(CajaPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConexionLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConexionLayout.createSequentialGroup()
                                .addComponent(btnConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))))
            .addGroup(PanelConexionLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        Conexion.addTab("Conexion SGBD", PanelConexion);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pestañaLexico)
                            .addComponent(pestañaInicial)
                            .addComponent(Conexion))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Conexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(pestañaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pestañaLexico, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pestañaLexico.getAccessibleContext().setAccessibleName("Léxico");
        Conexion.getAccessibleContext().setAccessibleName("Conexion");

        jScrollPane7.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadenaActionPerformed

    private void LexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LexicoActionPerformed
        controlError = 0;

        String c, resultado = " ";
        c = cadena.getText();
        StringTokenizer st = new StringTokenizer(c, " ");
        System.out.println(c);
        while (st.hasMoreTokens()) {

            String palabra = st.nextToken();
            if (Character.isDigit(palabra.charAt(0))) {
                n.checarNum(palabra);
                resultado = resultado + "*  " + palabra + "      " + n.obtenerNum() + "\n\n";
                if (n.obtenerValidador() == 1) {
                    controlError++;
                }
            } else { ///aqui me kede
                v.verificar(palabra);
                resultado = resultado + "*  " + palabra + "      " + v.obtenerVerificacion() + "\n\n";
                if (v.obtenerValidador() == 1) {
                    controlError++;
                }
            }
            // System.out.println(cont+" "+palabra);
            //cont++;

        }

        System.out.println("Control error: " + controlError);

            if (controlError == 0) {
                resultadosLexico.setForeground(Color.GREEN);
                resultadosLexico.setText(resultado);
                Sintactico.setEnabled(true);
            } else {
                resultadosLexico.setForeground(Color.RED);
                resultadosLexico.setText(resultado);
                Sintactico.setEnabled(false);
                resultadosSintactico.setText("");
                resultadosSemantico.setText("");
            }
        

        
    }//GEN-LAST:event_LexicoActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
         cadena.setText("");
        resultadosSintactico.setText("");
        resultadosLexico.setText("");
        resultadosSemantico.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      JOptionPane.showMessageDialog(null,"Elaborado por:\n"+
                                          "*   Alva Zamora David Emmanuel\n"+
                                          "*   Escoto Hernández Juan Luis\n"+
                                          "*   Espitia Rico Daniel\n"+
                                          "*   Mendez Medina Jorge\n"+
                                          "Ing.en Sistemas Computacionales\n"+
                                          "Instituto Tecnológico de Celaya");
       System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SintacticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SintacticoActionPerformed
      Semantico.setEnabled(true);
        int control=0;
        
        String c, resultado = " ";

        c = cadena.getText();
        System.out.println(c);

        StringTokenizer st = new StringTokenizer(c, " ");

        String palabra = st.nextToken();

        if (palabra.toLowerCase().equals("actualizar")) {
            u.verificarUpdate(c);
            resultado = u.obtenerUpdate();
            control=u.obtenerValidador();
        } else if (palabra.toLowerCase().equals("borrar")) {
            d.Analizar_Delete(c);
            resultado = d.RevDelete();
            control=d.obtenerValidador();
        } else if (palabra.toLowerCase().equals("insertar")) {
            i.verificarinsert(c);
            resultado = i.obtenerVerificacion();
            control=i.obtenerValidador();
        } else if (palabra.toLowerCase().equals("seleccionar")) {
            s.AnalizarSeleccionar(c);
            resultado = s.obtenerSelect();
            control=s.obtenerValidador();
        } else {
            resultado = "Sentencia Incorrecta Dentro del Lenguaje se esperaba al inicio un:\n" + "\n* Insertar" + "\n* Seleccionar" + "\n* Actualizar" + "\n* Borrar";
        }

 if (control == 1) {
                resultadosSintactico.setForeground(Color.GREEN);
                resultadosSintactico.setText(resultado);
                Semantico.setEnabled(true);
            } else {
                resultadosSintactico.setForeground(Color.RED);
                resultadosSintactico.setText(resultado);
                Semantico.setEnabled(false);
                resultadosSemantico.setText("");
            }
    }//GEN-LAST:event_SintacticoActionPerformed

    private void btnConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConexionActionPerformed
        if(!"".equals(SQLEspañol.CajaUsuario.getText()) && !"".equals(SQLEspañol.CajaPass.getText())){
           Cxn=new ConexionBD();
        }else
        JOptionPane.showMessageDialog(null, "Campos Incompletos: Ingresar Usuario y Contraseña");
    }//GEN-LAST:event_btnConexionActionPerformed

    private void btnBasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBasesActionPerformed
        if (bandera) {
             ConexionBD.Mostrar();
             bandera=false;
        }
    }//GEN-LAST:event_btnBasesActionPerformed

    private void ListaBasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaBasesActionPerformed
        //System.out.println(ListaBases.getSelectedItem().toString());
        if (SQLEspañol.ListaBases.getSelectedIndex()!= 0) {
            ConexionBD.SeleccionarBD(ListaBases.getSelectedItem().toString());
             ConexionBD.MostrarTablas();
        }else
            JOptionPane.showMessageDialog(null, "Selecciona Un Base de Datos a Usar");
    }//GEN-LAST:event_ListaBasesActionPerformed

    private void ArbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArbolMouseClicked
        // TODO add your handling code here:
        System.out.println(SQLEspañol.Arbol.getSelectionCount());
    }//GEN-LAST:event_ArbolMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SQLEspañol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SQLEspañol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SQLEspañol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SQLEspañol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SQLEspañol().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTree Arbol;
    public static javax.swing.JPasswordField CajaPass;
    public static javax.swing.JTextField CajaUsuario;
    private javax.swing.JTabbedPane Conexion;
    private javax.swing.JLabel LblBaseUso;
    private javax.swing.JLabel LblBases;
    private javax.swing.JLabel LblPass;
    private javax.swing.JLabel LblUsuario;
    private javax.swing.JButton Lexico;
    private javax.swing.JButton Limpiar;
    public static javax.swing.JComboBox ListaBases;
    private javax.swing.JPanel PanelConexion;
    private javax.swing.JButton Semantico;
    private javax.swing.JButton Sintactico;
    public static javax.swing.JButton btnBases;
    private javax.swing.JButton btnConexion;
    private javax.swing.JTextField cadena;
    private javax.swing.JTextArea consulta;
    private javax.swing.JButton consultaSQL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JTabbedPane pestañaInicial;
    private javax.swing.JTabbedPane pestañaLexico;
    private javax.swing.JTextArea resultadosLexico;
    private javax.swing.JTextArea resultadosSemantico;
    private javax.swing.JTextArea resultadosSintactico;
    // End of variables declaration//GEN-END:variables
}
